#!/usr/bin/python
import os, sys
from wallaby import *
    
Arm = 3
Arm_back = 2000
Arm_up = 500
Arm_down = 250
    
Claw = 2
Claw_open = 2000
Claw_close = 1100
            
def move_servo_slow(port, start_pos, end_pos, step):
	if  end_pos < start_pos:
		step=-step
  	for pos in range(start_pos, end_pos, step):
		set_servo_position(port, pos)
		msleep(50)
 	set_servo_position(port, end_pos)
            
##############################            

def arm_back(step):
	move_servo_slow(Arm, get_servo_position(Arm), Arm_back, step)
	msleep(750)
    
def arm_up(step):
	move_servo_slow(Arm, get_servo_position(Arm), Arm_up, step)

def arm_down(step):
	move_servo_slow(Arm, get_servo_position(Arm), Arm_down, step)


#############################


        
def open_claw(step):
	move_servo_slow(Claw, get_servo_position(Claw), Claw_open, step)
   
def close_claw(step):
  	move_servo_slow(Claw, get_servo_position(Claw), Claw_close, step)

        
############################
        
def move_box(position):
	set_servo_position(Box, position)
	msleep(750)
        
def carry_box(step):
	move_servo_slow(Box,get_servo_position(Box), Box_back, step)
        
def down_box(step):
	move_servo_slow(Box,get_servo_position(Box), Box_down, step)
